### ISSUE TITLE
Bug loading or reloading my plugin

### ISSUE THREAD

**Issue by Homegan** [rylinaux/PlugMan#19]
Hello, when I load or reload my plugin, this'm getting this error.
http://pastebin.com/skTwaRWy
No problem when I restarts the server, the plugin works him.
My plugins.yml http://pastebin.com/qmsKkw7d
And main class  http://pastebin.com/pyixxQvn
Otherwise, I use 1.7.10 cauldron and no problem with other plugins and plugman.
Best regards

**Comment by rylinaux** [comment]
Hello,


I don’t think this is an issue with PlugMan itself, but rather an issue that is occurring under the covers of Cauldron/Spigot. You can see that the error that starts on line 28 causes the error that starts on line 18 which causes the error that starts on line 2. 


The plugin that you’re trying to unload is pretty darn simple and where the error is caused by Cauldron/Spigot itself, I’m not sure there is anything I can do. I’ve never dealt with Cauldron before, so I have no idea what is going on with the re-mapping it is talking about.


Sorry for the lack of solution, but I believe the error lies within the internals of Cauldron/Spigot - PlugMan merely exposes the error.


Regards,

Ryan






From: Homegan
Sent: ‎Wednesday‎, ‎July‎ ‎22‎, ‎2015 ‎4‎:‎51‎ ‎PM
To: rylinaux/PlugMan





Hello, when I load or reload my plugin, this'm getting this error.
http://pastebin.com/skTwaRWy
No problem when I restarts the server, the plugin works him.
My plugins.yml http://pastebin.com/qmsKkw7d
And main class http://pastebin.com/pyixxQvn
Otherwise, I use 1.7.10 cauldron and no problem with other plugins and plugman.
Best regards
